### ISSUE TITLE
DIS PDU receive human readable 

### ISSUE THREAD

**Issue by Radnix666** [open-dis/open-dis-csharp#5]
C#: After doing the tutorials for EspduSender / EspduReceiver, I'm wondering what the next step to process the received PDU xml data to human readable form. Do I need to cross reference it with a database? Any suggestions highly appreciated.

**Comment by leif81** [comment]
@Radnix666 I'm not very familiar with the C# implementation. But if it's like the other language implementations once you get a Pdu you access the properties like location, orientation, etc. For the other fields like Country you could try using the Enumerations:

https://github.com/open-dis/open-dis-csharp/tree/master/C%23/DIS%232.0/OpenDis/Enumerations

**Comment by Radnix666** [comment]
Will do that. Thank you  leif81.
